services:
  back:
    build:
      context: ./back
    ports:
      - 3000:3000
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:dev

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=olympe
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  postgres_db:
